config/routes.rb
Rails.application.routes.draw do

  resources :debts
  resources :users do
    resources :transactions
  end

end

app/models/debt.rb
class Debt < ActiveRecord::Base
  belongs_to :user
  belongs_to :transaction
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :debt
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :transactions
  has_many :debts, through: :transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
  before_action :set_debt, only: [:show, :edit, :update, :destroy]

  # GET /debts
  # GET /debts.json
  def index
    @debts = Debt.all
  end

  # GET /debts/1
  # GET /debts/1.json
  def show
  end

  # GET /debts/new
  def new
    @debt = Debt.new
  end

  # GET /debts/1/edit
  def edit
  end

  # POST /debts
  # POST /debts.json
  def create
    @debt = Debt.new(debt_params)

    respond_to do |format|
      if @debt.save
        format.html { redirect_to @debt, notice: 'Debt was successfully created.' }
        format.json { render :show, status: :created, location: @debt }
      else
        format.html { render :new }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debts/1
  # PATCH/PUT /debts/1.json
  def update
    respond_to do |format|
      if @debt.update(debt_params)
        format.html { redirect_to @debt, notice: 'Debt was successfully updated.' }
        format.json { render :show, status: :ok, location: @debt }
      else
        format.html { render :edit }
        format.json { render json: @debt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debts/1
  # DELETE /debts/1.json
  def destroy
    @debt.destroy
    respond_to do |format|
      format.html { redirect_to debts_url, notice: 'Debt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debt
      @debt = Debt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debt_params
      params.require(:debt).permit(:amount, :user_to, :user_from)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    to = User.find(transaction_params[:to])
    @transaction = @user.transactions.create(transaction_params)
    redirect_to user_path(@user)
  end

  private
    def transaction_params
      params.require(:transaction).permit(:to, :amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/debts/_form.html.haml
= form_for @debt do |f|
  - if @debt.errors.any?
    #error_explanation
      %h2= "#{pluralize(@debt.errors.count, "error")} prohibited this debt from being saved:"
      %ul
        - @debt.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :user_to
    = f.text_field :user_to
  .field
    = f.label :user_from
    = f.text_field :user_from
  .actions
    = f.submit 'Save'

app/views/debts/edit.html.haml
%h1 Editing debt

= render 'form'

= link_to 'Show', @debt
\|
= link_to 'Back', debts_path

app/views/debts/index.html.haml
%h1 Listing debts

%table
  %thead
    %tr
      %th Amount
      %th User to
      %th User from
      %th
      %th
      %th

  %tbody
    - @debts.each do |debt|
      %tr
        %td= debt.amount
        %td= debt.user_to
        %td= debt.user_from
        %td= link_to 'Show', debt
        %td= link_to 'Edit', edit_debt_path(debt)
        %td= link_to 'Destroy', debt, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Debt', new_debt_path

app/views/debts/new.html.haml
%h1 New debt

= render 'form'

= link_to 'Back', debts_path

app/views/debts/show.html.haml
%p#notice= notice

%p
  %b Amount:
  = @debt.amount
%p
  %b User to:
  = @debt.user_to
%p
  %b User from:
  = @debt.user_from

= link_to 'Edit', edit_debt_path(@debt)
\|
= link_to 'Back', debts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title IouApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name

%p
  %b Transactions

  %p
    %b To
    - @user.transactions.each do |t|
      %p= "#{User.find(t.to).name}, #{t.amount} cents"

  %p
    %b From
    - Transaction.where(to: @user.id).each do |t|
      %p= User.find(t.user_id).name

  %p
    %b New Transactions
    = form_for ([@user, @user.transactions.build]) do |f|
      %p
        = f.label :to
        = f.select :to, User.where.not(id: @user.id).map { |u| [u.name, u.id] }
      %p
        = f.label :amount
        = f.number_field :amount
      = f.submit

%p
  = link_to 'Edit', edit_user_path(@user)
  \|
  = link_to 'Back', users_path